name: easy_cron
description: Parse cron string to schedule and generate previous or next schedule item.
version: 0.9.1
repository: https://github.com/karbunkul/dart_easy_cron

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  equatable: ^2.0.3
